
namespace Clinic_Mang_Sys.Forms
{
    partial class FrmClinic
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmClinic));
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject1 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject1 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject2 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject2 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject3 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject3 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject4 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject4 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject5 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject5 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject6 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject6 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject7 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject7 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject8 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject8 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject9 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject9 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Kimtoo.ValidationProvider.ValidationObject validationObject10 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject10 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject11 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject11 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject12 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject12 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Kimtoo.ValidationProvider.ValidationObject validationObject13 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject13 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject14 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject14 = new Kimtoo.ValidationProvider.ValidationObject();
            this.bunifuAppBar1 = new Bunifu.Utils.BunifuAppBar();
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bindingProvider1 = new Kimtoo.BindingProvider.BindingProvider();
            this.label1 = new System.Windows.Forms.Label();
            this.NameTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.AddressTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.PhoneTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.EmailTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.buttonSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label5 = new System.Windows.Forms.Label();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.buttonChangeLogo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.picLogo = new System.Windows.Forms.PictureBox();
            this.validationProvider1 = new Kimtoo.ValidationProvider.ValidationProvider();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            ((System.ComponentModel.ISupportInitialize)(this.picLogo)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuAppBar1
            // 
            this.bunifuAppBar1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.bunifuAppBar1.ControlBoxColor = System.Drawing.Color.Gray;
            this.bunifuAppBar1.ControlBoxColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(30)))), ((int)(((byte)(45)))));
            this.bunifuAppBar1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuAppBar1.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuAppBar1.ForeColor = System.Drawing.Color.Gray;
            this.bunifuAppBar1.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuAppBar1.Icon")));
            bindingObject1.Data = "";
            bindingObject1.Property = "Text";
            bindingObject1.TwoWay = true;
            this.bindingProvider1.SetLink(this.bunifuAppBar1, bindingObject1);
            validationObject1.CustomErrorMessage = "";
            validationObject1.Optional = false;
            validationObject1.PropertyName = "Text";
            validationObject1.Regex = null;
            validationObject1.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.bunifuAppBar1, validationObject1);
            this.bunifuAppBar1.Location = new System.Drawing.Point(0, 0);
            this.bunifuAppBar1.Name = "bunifuAppBar1";
            this.bunifuAppBar1.Size = new System.Drawing.Size(600, 46);
            this.bunifuAppBar1.TabIndex = 2;
            this.bunifuAppBar1.Title = "Clinic";
            this.bunifuAppBar1.TitleMargin = new System.Windows.Forms.Padding(47, 12, 0, 0);
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.Gray;
            bindingObject2.Data = "";
            bindingObject2.Property = "Text";
            bindingObject2.TwoWay = true;
            this.bindingProvider1.SetLink(this.label1, bindingObject2);
            validationObject2.CustomErrorMessage = "";
            validationObject2.Optional = false;
            validationObject2.PropertyName = "Text";
            validationObject2.Regex = null;
            validationObject2.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.label1, validationObject2);
            this.label1.Location = new System.Drawing.Point(35, 270);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(50, 20);
            this.label1.TabIndex = 5;
            this.label1.Text = "Name";
            // 
            // NameTextBox
            // 
            this.NameTextBox.AcceptsReturn = false;
            this.NameTextBox.AcceptsTab = false;
            this.NameTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.NameTextBox.AnimationSpeed = 200;
            this.NameTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.NameTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.NameTextBox.BackColor = System.Drawing.Color.Transparent;
            this.NameTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NameTextBox.BackgroundImage")));
            this.NameTextBox.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.NameTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NameTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NameTextBox.BorderColorIdle = System.Drawing.Color.LightGray;
            this.NameTextBox.BorderRadius = 35;
            this.NameTextBox.BorderThickness = 1;
            this.NameTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.NameTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.NameTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.NameTextBox.DefaultText = "";
            this.NameTextBox.FillColor = System.Drawing.Color.LightGray;
            this.NameTextBox.HideSelection = true;
            this.NameTextBox.IconLeft = null;
            this.NameTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.NameTextBox.IconPadding = 10;
            this.NameTextBox.IconRight = null;
            this.NameTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.NameTextBox.Lines = new string[0];
            bindingObject3.Data = "Name";
            bindingObject3.Property = "Text";
            bindingObject3.TwoWay = true;
            this.bindingProvider1.SetLink(this.NameTextBox, bindingObject3);
            validationObject3.CustomErrorMessage = "";
            validationObject3.Optional = false;
            validationObject3.PropertyName = "Text";
            validationObject3.Regex = "^[a-z ,.\'-]+$";
            validationObject3.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.Name;
            this.validationProvider1.SetLink(this.NameTextBox, validationObject3);
            this.NameTextBox.Location = new System.Drawing.Point(117, 263);
            this.NameTextBox.MaxLength = 32767;
            this.NameTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.NameTextBox.Modified = false;
            this.NameTextBox.Multiline = false;
            this.NameTextBox.Name = "NameTextBox";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameTextBox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.NameTextBox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameTextBox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.LightGray;
            stateProperties4.FillColor = System.Drawing.Color.LightGray;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameTextBox.OnIdleState = stateProperties4;
            this.NameTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.NameTextBox.PasswordChar = '\0';
            this.NameTextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.NameTextBox.PlaceholderText = "";
            this.NameTextBox.ReadOnly = false;
            this.NameTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.NameTextBox.SelectedText = "";
            this.NameTextBox.SelectionLength = 0;
            this.NameTextBox.SelectionStart = 0;
            this.NameTextBox.ShortcutsEnabled = true;
            this.NameTextBox.Size = new System.Drawing.Size(457, 36);
            this.NameTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.NameTextBox.TabIndex = 4;
            this.NameTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.NameTextBox.TextMarginBottom = 0;
            this.NameTextBox.TextMarginLeft = 3;
            this.NameTextBox.TextMarginTop = 0;
            this.NameTextBox.TextPlaceholder = "";
            this.NameTextBox.UseSystemPasswordChar = false;
            this.NameTextBox.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.Gray;
            bindingObject4.Data = "";
            bindingObject4.Property = "Text";
            bindingObject4.TwoWay = true;
            this.bindingProvider1.SetLink(this.label4, bindingObject4);
            validationObject4.CustomErrorMessage = "";
            validationObject4.Optional = false;
            validationObject4.PropertyName = "Text";
            validationObject4.Regex = null;
            validationObject4.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.label4, validationObject4);
            this.label4.Location = new System.Drawing.Point(35, 471);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(63, 20);
            this.label4.TabIndex = 10;
            this.label4.Text = "Address";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.Gray;
            bindingObject5.Data = "";
            bindingObject5.Property = "Text";
            bindingObject5.TwoWay = true;
            this.bindingProvider1.SetLink(this.label2, bindingObject5);
            validationObject5.CustomErrorMessage = "";
            validationObject5.Optional = false;
            validationObject5.PropertyName = "Text";
            validationObject5.Regex = null;
            validationObject5.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.label2, validationObject5);
            this.label2.Location = new System.Drawing.Point(35, 337);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(53, 20);
            this.label2.TabIndex = 11;
            this.label2.Text = "Phone";
            // 
            // AddressTextBox
            // 
            this.AddressTextBox.AcceptsReturn = false;
            this.AddressTextBox.AcceptsTab = false;
            this.AddressTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.AddressTextBox.AnimationSpeed = 200;
            this.AddressTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AddressTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AddressTextBox.BackColor = System.Drawing.Color.Transparent;
            this.AddressTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AddressTextBox.BackgroundImage")));
            this.AddressTextBox.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.AddressTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddressTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AddressTextBox.BorderColorIdle = System.Drawing.Color.LightGray;
            this.AddressTextBox.BorderRadius = 35;
            this.AddressTextBox.BorderThickness = 1;
            this.AddressTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AddressTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AddressTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AddressTextBox.DefaultText = "";
            this.AddressTextBox.FillColor = System.Drawing.Color.LightGray;
            this.AddressTextBox.HideSelection = true;
            this.AddressTextBox.IconLeft = null;
            this.AddressTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AddressTextBox.IconPadding = 10;
            this.AddressTextBox.IconRight = null;
            this.AddressTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AddressTextBox.Lines = new string[0];
            bindingObject6.Data = "Address";
            bindingObject6.Property = "Text";
            bindingObject6.TwoWay = true;
            this.bindingProvider1.SetLink(this.AddressTextBox, bindingObject6);
            validationObject6.CustomErrorMessage = "";
            validationObject6.Optional = false;
            validationObject6.PropertyName = "Text";
            validationObject6.Regex = "(.|\\s)*\\S(.|\\s)*";
            validationObject6.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.NotEmpty;
            this.validationProvider1.SetLink(this.AddressTextBox, validationObject6);
            this.AddressTextBox.Location = new System.Drawing.Point(116, 464);
            this.AddressTextBox.MaxLength = 32767;
            this.AddressTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.AddressTextBox.Modified = false;
            this.AddressTextBox.Multiline = false;
            this.AddressTextBox.Name = "AddressTextBox";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AddressTextBox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AddressTextBox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AddressTextBox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.LightGray;
            stateProperties8.FillColor = System.Drawing.Color.LightGray;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AddressTextBox.OnIdleState = stateProperties8;
            this.AddressTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.AddressTextBox.PasswordChar = '\0';
            this.AddressTextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AddressTextBox.PlaceholderText = "";
            this.AddressTextBox.ReadOnly = false;
            this.AddressTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AddressTextBox.SelectedText = "";
            this.AddressTextBox.SelectionLength = 0;
            this.AddressTextBox.SelectionStart = 0;
            this.AddressTextBox.ShortcutsEnabled = true;
            this.AddressTextBox.Size = new System.Drawing.Size(458, 36);
            this.AddressTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AddressTextBox.TabIndex = 9;
            this.AddressTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AddressTextBox.TextMarginBottom = 0;
            this.AddressTextBox.TextMarginLeft = 3;
            this.AddressTextBox.TextMarginTop = 0;
            this.AddressTextBox.TextPlaceholder = "";
            this.AddressTextBox.UseSystemPasswordChar = false;
            this.AddressTextBox.WordWrap = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.Gray;
            bindingObject7.Data = "";
            bindingObject7.Property = "Text";
            bindingObject7.TwoWay = true;
            this.bindingProvider1.SetLink(this.label3, bindingObject7);
            validationObject7.CustomErrorMessage = "";
            validationObject7.Optional = false;
            validationObject7.PropertyName = "Text";
            validationObject7.Regex = null;
            validationObject7.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.label3, validationObject7);
            this.label3.Location = new System.Drawing.Point(35, 404);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(46, 20);
            this.label3.TabIndex = 7;
            this.label3.Text = "Email";
            // 
            // PhoneTextBox
            // 
            this.PhoneTextBox.AcceptsReturn = false;
            this.PhoneTextBox.AcceptsTab = false;
            this.PhoneTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.PhoneTextBox.AnimationSpeed = 200;
            this.PhoneTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PhoneTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PhoneTextBox.BackColor = System.Drawing.Color.Transparent;
            this.PhoneTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PhoneTextBox.BackgroundImage")));
            this.PhoneTextBox.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.PhoneTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PhoneTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PhoneTextBox.BorderColorIdle = System.Drawing.Color.LightGray;
            this.PhoneTextBox.BorderRadius = 35;
            this.PhoneTextBox.BorderThickness = 1;
            this.PhoneTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PhoneTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PhoneTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.PhoneTextBox.DefaultText = "";
            this.PhoneTextBox.FillColor = System.Drawing.Color.LightGray;
            this.PhoneTextBox.HideSelection = true;
            this.PhoneTextBox.IconLeft = null;
            this.PhoneTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PhoneTextBox.IconPadding = 10;
            this.PhoneTextBox.IconRight = null;
            this.PhoneTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PhoneTextBox.Lines = new string[0];
            bindingObject8.Data = "Phone";
            bindingObject8.Property = "Text";
            bindingObject8.TwoWay = true;
            this.bindingProvider1.SetLink(this.PhoneTextBox, bindingObject8);
            validationObject8.CustomErrorMessage = "";
            validationObject8.Optional = false;
            validationObject8.PropertyName = "Text";
            validationObject8.Regex = "^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$";
            validationObject8.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.Phone;
            this.validationProvider1.SetLink(this.PhoneTextBox, validationObject8);
            this.PhoneTextBox.Location = new System.Drawing.Point(116, 330);
            this.PhoneTextBox.MaxLength = 32767;
            this.PhoneTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.PhoneTextBox.Modified = false;
            this.PhoneTextBox.Multiline = false;
            this.PhoneTextBox.Name = "PhoneTextBox";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PhoneTextBox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PhoneTextBox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PhoneTextBox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.LightGray;
            stateProperties12.FillColor = System.Drawing.Color.LightGray;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PhoneTextBox.OnIdleState = stateProperties12;
            this.PhoneTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.PhoneTextBox.PasswordChar = '\0';
            this.PhoneTextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.PhoneTextBox.PlaceholderText = "";
            this.PhoneTextBox.ReadOnly = false;
            this.PhoneTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PhoneTextBox.SelectedText = "";
            this.PhoneTextBox.SelectionLength = 0;
            this.PhoneTextBox.SelectionStart = 0;
            this.PhoneTextBox.ShortcutsEnabled = true;
            this.PhoneTextBox.Size = new System.Drawing.Size(458, 36);
            this.PhoneTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PhoneTextBox.TabIndex = 6;
            this.PhoneTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PhoneTextBox.TextMarginBottom = 0;
            this.PhoneTextBox.TextMarginLeft = 3;
            this.PhoneTextBox.TextMarginTop = 0;
            this.PhoneTextBox.TextPlaceholder = "";
            this.PhoneTextBox.UseSystemPasswordChar = false;
            this.PhoneTextBox.WordWrap = true;
            // 
            // EmailTextBox
            // 
            this.EmailTextBox.AcceptsReturn = false;
            this.EmailTextBox.AcceptsTab = false;
            this.EmailTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.EmailTextBox.AnimationSpeed = 200;
            this.EmailTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.EmailTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.EmailTextBox.BackColor = System.Drawing.Color.Transparent;
            this.EmailTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("EmailTextBox.BackgroundImage")));
            this.EmailTextBox.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.EmailTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EmailTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.EmailTextBox.BorderColorIdle = System.Drawing.Color.LightGray;
            this.EmailTextBox.BorderRadius = 35;
            this.EmailTextBox.BorderThickness = 1;
            this.EmailTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.EmailTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.EmailTextBox.DefaultText = "";
            this.EmailTextBox.FillColor = System.Drawing.Color.LightGray;
            this.EmailTextBox.HideSelection = true;
            this.EmailTextBox.IconLeft = null;
            this.EmailTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailTextBox.IconPadding = 10;
            this.EmailTextBox.IconRight = null;
            this.EmailTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailTextBox.Lines = new string[0];
            bindingObject9.Data = "Email";
            bindingObject9.Property = "Text";
            bindingObject9.TwoWay = true;
            this.bindingProvider1.SetLink(this.EmailTextBox, bindingObject9);
            validationObject9.CustomErrorMessage = "";
            validationObject9.Optional = false;
            validationObject9.PropertyName = "Text";
            validationObject9.Regex = resources.GetString("validationObject9.Regex");
            validationObject9.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.Email;
            this.validationProvider1.SetLink(this.EmailTextBox, validationObject9);
            this.EmailTextBox.Location = new System.Drawing.Point(116, 397);
            this.EmailTextBox.MaxLength = 32767;
            this.EmailTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.EmailTextBox.Modified = false;
            this.EmailTextBox.Multiline = false;
            this.EmailTextBox.Name = "EmailTextBox";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailTextBox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.EmailTextBox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailTextBox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.LightGray;
            stateProperties16.FillColor = System.Drawing.Color.LightGray;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailTextBox.OnIdleState = stateProperties16;
            this.EmailTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.EmailTextBox.PasswordChar = '\0';
            this.EmailTextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.EmailTextBox.PlaceholderText = "";
            this.EmailTextBox.ReadOnly = false;
            this.EmailTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.EmailTextBox.SelectedText = "";
            this.EmailTextBox.SelectionLength = 0;
            this.EmailTextBox.SelectionStart = 0;
            this.EmailTextBox.ShortcutsEnabled = true;
            this.EmailTextBox.Size = new System.Drawing.Size(458, 36);
            this.EmailTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.EmailTextBox.TabIndex = 8;
            this.EmailTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.EmailTextBox.TextMarginBottom = 0;
            this.EmailTextBox.TextMarginLeft = 3;
            this.EmailTextBox.TextMarginTop = 0;
            this.EmailTextBox.TextPlaceholder = "";
            this.EmailTextBox.UseSystemPasswordChar = false;
            this.EmailTextBox.WordWrap = true;
            // 
            // buttonSave
            // 
            this.buttonSave.AllowAnimations = true;
            this.buttonSave.AllowMouseEffects = true;
            this.buttonSave.AllowToggling = false;
            this.buttonSave.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonSave.AnimationSpeed = 200;
            this.buttonSave.AutoGenerateColors = false;
            this.buttonSave.AutoRoundBorders = false;
            this.buttonSave.AutoSizeLeftIcon = true;
            this.buttonSave.AutoSizeRightIcon = true;
            this.buttonSave.BackColor = System.Drawing.Color.Transparent;
            this.buttonSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(30)))), ((int)(((byte)(45)))));
            this.buttonSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonSave.BackgroundImage")));
            this.buttonSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonSave.ButtonText = "SAVE";
            this.buttonSave.ButtonTextMarginLeft = 0;
            this.buttonSave.ColorContrastOnClick = 45;
            this.buttonSave.ColorContrastOnHover = 45;
            this.buttonSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.buttonSave.CustomizableEdges = borderEdges1;
            this.buttonSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonSave.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonSave.ForeColor = System.Drawing.Color.White;
            this.buttonSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonSave.IconMarginLeft = 11;
            this.buttonSave.IconPadding = 10;
            this.buttonSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonSave.IconSize = 25;
            this.buttonSave.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.buttonSave.IdleBorderRadius = 35;
            this.buttonSave.IdleBorderThickness = 1;
            this.buttonSave.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(30)))), ((int)(((byte)(45)))));
            this.buttonSave.IdleIconLeftImage = null;
            this.buttonSave.IdleIconRightImage = null;
            this.buttonSave.IndicateFocus = false;
            validationObject10.CustomErrorMessage = "";
            validationObject10.Optional = false;
            validationObject10.PropertyName = "Text";
            validationObject10.Regex = null;
            validationObject10.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.buttonSave, validationObject10);
            bindingObject10.Data = "";
            bindingObject10.Property = "Text";
            bindingObject10.TwoWay = true;
            this.bindingProvider1.SetLink(this.buttonSave, bindingObject10);
            this.buttonSave.Location = new System.Drawing.Point(480, 615);
            this.buttonSave.Name = "buttonSave";
            this.buttonSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonSave.OnDisabledState.BorderRadius = 35;
            this.buttonSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonSave.OnDisabledState.BorderThickness = 1;
            this.buttonSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonSave.OnDisabledState.IconLeftImage = null;
            this.buttonSave.OnDisabledState.IconRightImage = null;
            this.buttonSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonSave.onHoverState.BorderRadius = 35;
            this.buttonSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonSave.onHoverState.BorderThickness = 1;
            this.buttonSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonSave.onHoverState.IconLeftImage = null;
            this.buttonSave.onHoverState.IconRightImage = null;
            this.buttonSave.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.buttonSave.OnIdleState.BorderRadius = 35;
            this.buttonSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonSave.OnIdleState.BorderThickness = 1;
            this.buttonSave.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(30)))), ((int)(((byte)(45)))));
            this.buttonSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonSave.OnIdleState.IconLeftImage = null;
            this.buttonSave.OnIdleState.IconRightImage = null;
            this.buttonSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonSave.OnPressedState.BorderRadius = 35;
            this.buttonSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonSave.OnPressedState.BorderThickness = 1;
            this.buttonSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonSave.OnPressedState.IconLeftImage = null;
            this.buttonSave.OnPressedState.IconRightImage = null;
            this.buttonSave.Size = new System.Drawing.Size(102, 37);
            this.buttonSave.TabIndex = 12;
            this.buttonSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonSave.TextMarginLeft = 0;
            this.buttonSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonSave.UseDefaultRadiusAndThickness = true;
            this.buttonSave.Click += new System.EventHandler(this.buttonSave_Click);
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.Gray;
            bindingObject11.Data = "";
            bindingObject11.Property = "Text";
            bindingObject11.TwoWay = true;
            this.bindingProvider1.SetLink(this.label5, bindingObject11);
            validationObject11.CustomErrorMessage = "";
            validationObject11.Optional = false;
            validationObject11.PropertyName = "Text";
            validationObject11.Regex = null;
            validationObject11.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.label5, validationObject11);
            this.label5.Location = new System.Drawing.Point(35, 538);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(73, 20);
            this.label5.TabIndex = 14;
            this.label5.Text = "Password";
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.LightGray;
            this.bunifuTextBox1.BorderRadius = 35;
            this.bunifuTextBox1.BorderThickness = 1;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox1.DefaultText = "";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.LightGray;
            this.bunifuTextBox1.HideSelection = true;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[0];
            bindingObject12.Data = "Password";
            bindingObject12.Property = "Text";
            bindingObject12.TwoWay = true;
            this.bindingProvider1.SetLink(this.bunifuTextBox1, bindingObject12);
            validationObject12.CustomErrorMessage = "";
            validationObject12.Optional = false;
            validationObject12.PropertyName = "Text";
            validationObject12.Regex = "(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{6,}$";
            validationObject12.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.Password;
            this.validationProvider1.SetLink(this.bunifuTextBox1, validationObject12);
            this.bunifuTextBox1.Location = new System.Drawing.Point(117, 531);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.LightGray;
            stateProperties20.FillColor = System.Drawing.Color.LightGray;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnIdleState = stateProperties20;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox1.PasswordChar = '●';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox1.PlaceholderText = "";
            this.bunifuTextBox1.ReadOnly = false;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 0;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(458, 36);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox1.TabIndex = 13;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 3;
            this.bunifuTextBox1.TextMarginTop = 0;
            this.bunifuTextBox1.TextPlaceholder = "";
            this.bunifuTextBox1.UseSystemPasswordChar = true;
            this.bunifuTextBox1.WordWrap = true;
            // 
            // buttonChangeLogo
            // 
            this.buttonChangeLogo.AllowAnimations = true;
            this.buttonChangeLogo.AllowMouseEffects = true;
            this.buttonChangeLogo.AllowToggling = false;
            this.buttonChangeLogo.AnimationSpeed = 200;
            this.buttonChangeLogo.AutoGenerateColors = false;
            this.buttonChangeLogo.AutoRoundBorders = false;
            this.buttonChangeLogo.AutoSizeLeftIcon = true;
            this.buttonChangeLogo.AutoSizeRightIcon = true;
            this.buttonChangeLogo.BackColor = System.Drawing.Color.Transparent;
            this.buttonChangeLogo.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(30)))), ((int)(((byte)(45)))));
            this.buttonChangeLogo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonChangeLogo.BackgroundImage")));
            this.buttonChangeLogo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonChangeLogo.ButtonText = "Change";
            this.buttonChangeLogo.ButtonTextMarginLeft = 0;
            this.buttonChangeLogo.ColorContrastOnClick = 45;
            this.buttonChangeLogo.ColorContrastOnHover = 45;
            this.buttonChangeLogo.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.buttonChangeLogo.CustomizableEdges = borderEdges2;
            this.buttonChangeLogo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonChangeLogo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonChangeLogo.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonChangeLogo.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonChangeLogo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonChangeLogo.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonChangeLogo.ForeColor = System.Drawing.Color.White;
            this.buttonChangeLogo.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonChangeLogo.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonChangeLogo.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonChangeLogo.IconMarginLeft = 11;
            this.buttonChangeLogo.IconPadding = 10;
            this.buttonChangeLogo.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonChangeLogo.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonChangeLogo.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonChangeLogo.IconSize = 25;
            this.buttonChangeLogo.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.buttonChangeLogo.IdleBorderRadius = 35;
            this.buttonChangeLogo.IdleBorderThickness = 1;
            this.buttonChangeLogo.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(30)))), ((int)(((byte)(45)))));
            this.buttonChangeLogo.IdleIconLeftImage = null;
            this.buttonChangeLogo.IdleIconRightImage = null;
            this.buttonChangeLogo.IndicateFocus = false;
            validationObject13.CustomErrorMessage = "";
            validationObject13.Optional = false;
            validationObject13.PropertyName = "Text";
            validationObject13.Regex = null;
            validationObject13.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.buttonChangeLogo, validationObject13);
            bindingObject13.Data = "";
            bindingObject13.Property = "Text";
            bindingObject13.TwoWay = true;
            this.bindingProvider1.SetLink(this.buttonChangeLogo, bindingObject13);
            this.buttonChangeLogo.Location = new System.Drawing.Point(115, 192);
            this.buttonChangeLogo.Name = "buttonChangeLogo";
            this.buttonChangeLogo.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonChangeLogo.OnDisabledState.BorderRadius = 35;
            this.buttonChangeLogo.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonChangeLogo.OnDisabledState.BorderThickness = 1;
            this.buttonChangeLogo.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonChangeLogo.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonChangeLogo.OnDisabledState.IconLeftImage = null;
            this.buttonChangeLogo.OnDisabledState.IconRightImage = null;
            this.buttonChangeLogo.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonChangeLogo.onHoverState.BorderRadius = 35;
            this.buttonChangeLogo.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonChangeLogo.onHoverState.BorderThickness = 1;
            this.buttonChangeLogo.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonChangeLogo.onHoverState.ForeColor = System.Drawing.Color.White;
            this.buttonChangeLogo.onHoverState.IconLeftImage = null;
            this.buttonChangeLogo.onHoverState.IconRightImage = null;
            this.buttonChangeLogo.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.buttonChangeLogo.OnIdleState.BorderRadius = 35;
            this.buttonChangeLogo.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonChangeLogo.OnIdleState.BorderThickness = 1;
            this.buttonChangeLogo.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(30)))), ((int)(((byte)(45)))));
            this.buttonChangeLogo.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.buttonChangeLogo.OnIdleState.IconLeftImage = null;
            this.buttonChangeLogo.OnIdleState.IconRightImage = null;
            this.buttonChangeLogo.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonChangeLogo.OnPressedState.BorderRadius = 35;
            this.buttonChangeLogo.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonChangeLogo.OnPressedState.BorderThickness = 1;
            this.buttonChangeLogo.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonChangeLogo.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonChangeLogo.OnPressedState.IconLeftImage = null;
            this.buttonChangeLogo.OnPressedState.IconRightImage = null;
            this.buttonChangeLogo.Size = new System.Drawing.Size(147, 37);
            this.buttonChangeLogo.TabIndex = 15;
            this.buttonChangeLogo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonChangeLogo.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonChangeLogo.TextMarginLeft = 0;
            this.buttonChangeLogo.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonChangeLogo.UseDefaultRadiusAndThickness = true;
            this.buttonChangeLogo.Click += new System.EventHandler(this.buttonChangeLogo_Click);
            // 
            // picLogo
            // 
            this.picLogo.Image = ((System.Drawing.Image)(resources.GetObject("picLogo.Image")));
            bindingObject14.Data = "";
            bindingObject14.Property = "Text";
            bindingObject14.TwoWay = true;
            this.bindingProvider1.SetLink(this.picLogo, bindingObject14);
            validationObject14.CustomErrorMessage = "";
            validationObject14.Optional = false;
            validationObject14.PropertyName = "Text";
            validationObject14.Regex = null;
            validationObject14.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider1.SetLink(this.picLogo, validationObject14);
            this.picLogo.Location = new System.Drawing.Point(115, 64);
            this.picLogo.Name = "picLogo";
            this.picLogo.Size = new System.Drawing.Size(147, 122);
            this.picLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picLogo.TabIndex = 16;
            this.picLogo.TabStop = false;
            // 
            // validationProvider1
            // 
            this.validationProvider1.ErrorColor = System.Drawing.Color.Crimson;
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = false;
            this.bunifuFormDock1.ShowDockingIndicators = false;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // openFileDialog1
            // 
            this.openFileDialog1.Filter = "Image Files|*.bmp;*.jpg;*.jpeg;*.jpe;*.gif;*.png;*.tif;*.tiff";
            this.openFileDialog1.FileOk += new System.ComponentModel.CancelEventHandler(this.openFileDialog1_FileOk);
            // 
            // FrmClinic
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(251)))), ((int)(((byte)(252)))));
            this.ClientSize = new System.Drawing.Size(600, 680);
            this.Controls.Add(this.picLogo);
            this.Controls.Add(this.buttonChangeLogo);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.bunifuTextBox1);
            this.Controls.Add(this.buttonSave);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.AddressTextBox);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.PhoneTextBox);
            this.Controls.Add(this.EmailTextBox);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.NameTextBox);
            this.Controls.Add(this.bunifuAppBar1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MaximizeBox = false;
            this.MaximumSize = new System.Drawing.Size(800, 880);
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(600, 680);
            this.Name = "FrmClinic";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FrmClinic";
            ((System.ComponentModel.ISupportInitialize)(this.picLogo)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Utils.BunifuAppBar bunifuAppBar1;
        private Kimtoo.BindingProvider.BindingProvider bindingProvider1;
        private Kimtoo.ValidationProvider.ValidationProvider validationProvider1;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox NameTextBox;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox AddressTextBox;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox PhoneTextBox;
        private Bunifu.UI.WinForms.BunifuTextBox EmailTextBox;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonSave;
        private System.Windows.Forms.PictureBox picLogo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonChangeLogo;
        private System.Windows.Forms.OpenFileDialog openFileDialog1;
    }
}